### PR TITLE
[#27] Support GHC-8.6.3

### LINKED ISSUE #27: Support GHC-8.6.3
I tried to make it myself but some decisions should be made in here.

The thing is that the latest version of `stm` –– [`stm-2.5.0.0`](http://hackage.haskell.org/package/stm-2.5.0.0) has some breaking change in it, so the interface of the `capataz` library is conflicting with it. The Changelog for 2.5.0.0 says

> Switched newTBQueue and newTBQueueIO to accept Natural as size (gh-17)

And here is the error for `capataz`:

```haskell
Haskell-capataz/src/Control/Concurrent/Capataz/Util.hs:75:30: error:
        • Couldn't match expected type ‘Natural’ with actual type ‘Int’
        • In the first argument of ‘newTBQueueIO’, namely ‘bufferSize’
          In a stmt of a 'do' block: inputQueue <- newTBQueueIO bufferSize
          In the expression:
            do inputQueue <- newTBQueueIO bufferSize
               let myLogFunc = mkLogFunc $ ...
                   loggerSpec
                     = workerSpec
                         procName
                         (runLoggerThread logOptions inputQueue)
                         (modOptions . set workerRestartStrategyL Permanent)
               return (loggerSpec, myLogFunc)
       |
    75 |   inputQueue <- newTBQueueIO bufferSize
       |                              ^^^^^^^^^^
```

The old version of `stm` -- 2.4.5.1 is not compatible with GHC-8.6.3.
So I'm not sure how you'd like this to be solved but either way, this is going to be breaking for `capataz`, so the new release should be made in order to support building with GHC-8.6.3.

If you'd like I can continue working on this if we agree on the strategy. The question is: is it better to change the type of the `buildLogWorkerSpec` to receive `Natural` or only change the internal of the function?  Or probably you have some better ways to solve this?

### PR DESCRIPTION
**Pull request by vrom911**
Add `buildLogWorkerSpec1` and `buildLogWorkerOptions1` with `Natural` instead of `Int`.
Deprecate `buildLogWorkerSpec` and `buildLogWorkerOptions`

Resolves #27 

I am not really familiar with the semantic versioning, so hope `0.2.1.0` version makes sense here.
Let me know if I missed something, or some docs are require updates as well. 🙂

### CODE REVIEW

**Comment by vrom911** [comment]
Hello @roman!
Sorry for bothering, just friendly ping on this one :slightly_smiling_face: Does it require any further changes?

**Comment by roman** [comment]
Apologies for letting this rot for a while, great work!

**Comment by roman** [comment]
Also released a new version.

@vrom911  Would you like to be a maintainer on Hackage?

**Comment by vrom911** [comment]
@roman, thank you very much! 🙂 

I would be happy to help with maintaining, I am `vrom911` on Hackage.

**Pull request merged**
